name: Application_pipeline-ymal

on: 
  workflow_dispatch:

# run-name: ubuntu-latest

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-22.04
  
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
    
