name: Application_pipeline-ymal

on: 
  workflow_dispatch:

# run-name: ubuntu-latest

jobs:
  my_job:
    name: deploy to staging
    runs-on: self-hosted
    
  
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

    
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '16.17'
      
     
      - name: npm install and build
        run: |
          cd Application-data
          npm install
          npm run build
        env:
          CI: false
              
        
        
          
